### ISSUE TITLE
GPU?

### ISSUE THREAD

**Issue by alemelis** [ianshmean/Darknet.jl#7]
Hello!
two questions:
- are you planning to keep building the binaries every time AlexeyAB pushes to master?
- is GPU support planned? How can I help?

**Comment by ianshmean** [comment]
> are you planning to keep building the binaries every time AlexeyAB pushes to master?

I'd much rather provide builds for tagged releases. I have [an issue open](https://github.com/AlexeyAB/darknet/issues/2671) asking to move to semver releases, which really should be the case for such a well-used repo. I know it is on the todo list.

> is GPU support planned? How can I help?

Once the CUDA BinaryBuilder scripts are released, we should be able to build CUDA versions on the BinaryBuilder CI infrastructure.
The plan is to provide a CPU-only and a GPU image, and switch between the two without breaking on systems with no GPU. See the discussion here: https://github.com/AlexeyAB/darknet/issues/4323#issuecomment-555706770

You might also want to try out [ObjectDetector.jl](https://github.com/r3tex/ObjectDetector.jl). It's work in progress, but it's a fully-julia Flux & CuArrays-based implementation that can currently run v2-tiny, v3, v3-tiny models by reading .cfg & .weights files directly. No training yet though. It works well on CPU and GPU, although initial load times are a little slow.

Also, there's [YOLO.jl](https://github.com/ianshmean/YOLO.jl), which has a Knet backend, and might have training functionality soon, but currently only works for v2-tiny.

**Comment by alemelis** [comment]
thanks for all the links!
